#include "../include/audio.h"
#include <stddef.h>

static plat_sound *g_sfx[AUDIO_EVENT_COUNT];
static plat_music *g_music;

/* One path per event. mouseclick.wav is the original asset; the rest are
 * generated by scripts/gen_placeholder_assets.py, since the project shipped
 * with no other sounds at all. */
static const char *const SFX_PATH[AUDIO_EVENT_COUNT] = {
    "assets/audio/menu_move.wav",  /* AUDIO_MENU_MOVE  */
    "assets/audio/mouseclick.wav", /* AUDIO_MENU_CLICK */
    "assets/audio/jump.wav",       /* AUDIO_JUMP       */
    "assets/audio/damage.wav",     /* AUDIO_DAMAGE     */
    "assets/audio/goal.wav"        /* AUDIO_GOAL       */
};

/* Per-event mix levels, so the menu blip does not sit at the same loudness as
 * the goal fanfare. Fractions of the mixer maximum. */
static const int SFX_VOLUME[AUDIO_EVENT_COUNT] = {
    AUDIO_VOLUME_MAX / 5, AUDIO_VOLUME_MAX / 3, AUDIO_VOLUME_MAX / 4,
    AUDIO_VOLUME_MAX / 2, AUDIO_VOLUME_MAX / 2};

void audio_init(void) {
  int i;
  if (!plat_audio_ok()) {
    return;
  }
  for (i = 0; i < AUDIO_EVENT_COUNT; ++i) {
    g_sfx[i] = plat_sound_load(SFX_PATH[i]);
    if (g_sfx[i] != NULL) {
      plat_sound_volume(g_sfx[i], SFX_VOLUME[i]);
    }
  }
  /* OGG is preferred over MP3, and this is not a matter of taste.
   *
   * SDL_mixer 1.2's MP3 backend (music_mad, via libmad) reads past its own
   * decode buffer. AddressSanitizer catches it as a heap-buffer-overflow on
   * the mixer's audio thread: an 8464-byte read starting 1024 bytes past the
   * end of the 72112-byte region that mad_openFileRW allocated during
   * Mix_LoadMUS, inside mad_getSamples -> SDL_ConvertAudio. SDL_mixer 1.2.12
   * is from 2012 and unmaintained, so this will not be fixed upstream.
   *
   * That is almost certainly the "audio anomalies on modern Linux" in #17:
   * a decoder scribbling past its buffer produces exactly the noise and
   * instability that was reported, and the v0.2.0 changelog's attempt to fix
   * it by tuning Mix_OpenAudio parameters was treating a symptom.
   *
   * The OGG backend uses libvorbisfile, which is maintained and does not have
   * this defect. Converting the track sidesteps the buggy decoder entirely:
   *
   *     ffmpeg -i assets/audio/music.mp3 -c:a libvorbis -q:a 4 \
   *            assets/audio/music.ogg
   *
   * Drop that file in and this picks it up with no code change. Until then the
   * MP3 is used, because silence is worse than a decoder bug in a background
   * track -- but it is a known-bad path, not a supported one. */
  g_music = plat_music_load_optional("assets/audio/music.ogg");
  if (g_music == NULL) {
    g_music = plat_music_load("assets/audio/music.mp3");
  }
}

void audio_shutdown(void) {
  int i;
  plat_music_stop();
  plat_music_free(g_music);
  g_music = NULL;
  for (i = 0; i < AUDIO_EVENT_COUNT; ++i) {
    plat_sound_free(g_sfx[i]);
    g_sfx[i] = NULL;
  }
}

void audio_play(audio_event event) {
  if (event < 0 || event >= AUDIO_EVENT_COUNT) {
    return;
  }
  /* plat_sound_play already no-ops on a NULL chunk or a failed mixer, so a
   * missing sound is silent rather than a crash or a special case here. */
  plat_sound_play(g_sfx[event]);
}

void audio_music_start(void) {
  /* -1 loops forever. */
  plat_music_play(g_music, -1);
}

int audio_music_volume(int volume) {
  if (volume < 0) {
    volume = 0;
  }
  if (volume > AUDIO_VOLUME_MAX) {
    volume = AUDIO_VOLUME_MAX;
  }
  plat_music_volume(volume);
  return volume;
}
